#ifndef MW_RECEIVER_REV_B_PINS_H
#define MW_RECEIVER_REV_B_PINS_H

/*
 * Frozen receiver-effects Rev A0 GPIO/net contract for NINA-B302 open-CPU.
 * These definitions bind the independent receiver-effects PCB and target
 * adapter. Fabrication and target/HIL gates remain open until their evidence
 * closes. No wand pin, mechanical, PCB, or fabrication package is changed.
 */

/* GC9A01A 240x240 SPI display module, 8-pin connector. */
#define MW_RXFX_TFT_SCK_MODULE_PAD 52U
#define MW_RXFX_TFT_SCK_GPIO_PORT 0U
#define MW_RXFX_TFT_SCK_GPIO_PIN 19U
#define MW_RXFX_TFT_MOSI_MODULE_PAD 50U
#define MW_RXFX_TFT_MOSI_GPIO_PORT 0U
#define MW_RXFX_TFT_MOSI_GPIO_PIN 20U
#define MW_RXFX_TFT_CS_MODULE_PAD 51U
#define MW_RXFX_TFT_CS_GPIO_PORT 0U
#define MW_RXFX_TFT_CS_GPIO_PIN 17U
#define MW_RXFX_TFT_DC_MODULE_PAD 48U
#define MW_RXFX_TFT_DC_GPIO_PORT 0U
#define MW_RXFX_TFT_DC_GPIO_PIN 21U
#define MW_RXFX_TFT_RST_MODULE_PAD 49U
#define MW_RXFX_TFT_RST_GPIO_PORT 0U
#define MW_RXFX_TFT_RST_GPIO_PIN 22U
#define MW_RXFX_TFT_BL_MODULE_PAD 47U
#define MW_RXFX_TFT_BL_GPIO_PORT 0U
#define MW_RXFX_TFT_BL_GPIO_PIN 23U
#define MW_RXFX_TFT_CS_ACTIVE_LOW 1U
#define MW_RXFX_TFT_RESET_ACTIVE_LOW 1U
#define MW_RXFX_TFT_BL_GATE_ACTIVE_HIGH 1U

/* Locked Waveshare SKU 19192 J2 order: 3V3,GND,MOSI,SCK,CS,DC,RST,BL. */
#define MW_RXFX_TFT_J2_PIN_3_MOSI 3U
#define MW_RXFX_TFT_J2_PIN_4_SCK 4U
#define MW_RXFX_TFT_J2_PIN_5_CS 5U
#define MW_RXFX_TFT_J2_PIN_6_DC 6U
#define MW_RXFX_TFT_J2_PIN_7_RST 7U
#define MW_RXFX_TFT_J2_PIN_8_BL 8U

/* MAX98357A I2S class-D amplifier; SD/MODE has a hardware pull-down. */
#define MW_RXFX_I2S_BCLK_MODULE_PAD 1U
#define MW_RXFX_I2S_BCLK_GPIO_PORT 0U
#define MW_RXFX_I2S_BCLK_GPIO_PIN 13U
#define MW_RXFX_I2S_LRCLK_MODULE_PAD 2U
#define MW_RXFX_I2S_LRCLK_GPIO_PORT 0U
#define MW_RXFX_I2S_LRCLK_GPIO_PIN 14U
#define MW_RXFX_I2S_DOUT_MODULE_PAD 3U
#define MW_RXFX_I2S_DOUT_GPIO_PORT 0U
#define MW_RXFX_I2S_DOUT_GPIO_PIN 15U
#define MW_RXFX_AUDIO_SD_CTRL_MODULE_PAD 4U
#define MW_RXFX_AUDIO_SD_CTRL_GPIO_PORT 0U
#define MW_RXFX_AUDIO_SD_CTRL_GPIO_PIN 16U
#define MW_RXFX_AUDIO_SD_ENABLE_ACTIVE_HIGH 1U
#define MW_RXFX_AUDIO_SD_SERIES_OHMS 2200U
#define MW_RXFX_AUDIO_SD_PULLDOWN_OHMS 100000U

/* Compatibility aliases use the amplifier-side DIN/SD terminology. */
#define MW_RXFX_I2S_DIN_MODULE_PAD MW_RXFX_I2S_DOUT_MODULE_PAD
#define MW_RXFX_I2S_DIN_GPIO_PORT MW_RXFX_I2S_DOUT_GPIO_PORT
#define MW_RXFX_I2S_DIN_GPIO_PIN MW_RXFX_I2S_DOUT_GPIO_PIN
#define MW_RXFX_AUDIO_SD_MODULE_PAD MW_RXFX_AUDIO_SD_CTRL_MODULE_PAD
#define MW_RXFX_AUDIO_SD_GPIO_PORT MW_RXFX_AUDIO_SD_CTRL_GPIO_PORT
#define MW_RXFX_AUDIO_SD_GPIO_PIN MW_RXFX_AUDIO_SD_CTRL_GPIO_PIN

/* Discrete 3.3 V RGB LED with three current-limiting resistors. */
#define MW_RXFX_RGB_R_MODULE_PAD 5U
#define MW_RXFX_RGB_R_GPIO_PORT 0U
#define MW_RXFX_RGB_R_GPIO_PIN 24U
#define MW_RXFX_RGB_G_MODULE_PAD 7U
#define MW_RXFX_RGB_G_GPIO_PORT 0U
#define MW_RXFX_RGB_G_GPIO_PIN 25U
#define MW_RXFX_RGB_B_MODULE_PAD 8U
#define MW_RXFX_RGB_B_GPIO_PORT 1U
#define MW_RXFX_RGB_B_GPIO_PIN 0U
#define MW_RXFX_RGB_COMMON_ANODE 1U
#define MW_RXFX_RGB_ACTIVE_LOW 1U

#define MW_RXFX_TFT_WIDTH 240U
#define MW_RXFX_TFT_HEIGHT 240U
#define MW_RXFX_SPEAKER_MIN_OHMS 4U
#define MW_RXFX_REQUIRED_USB_SUPPLY_MV 5000U
#define MW_RXFX_REQUIRED_USB_SUPPLY_MA 2000U

#endif
